services:
  - type: web
    name: drive-cloud-storage
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json